### ISSUE TITLE
deadlock in release_pool_engine

### ISSUE THREAD

**Issue by Wouter1** [SWI-Prolog/issues#57] opened 2017-07-31 12:31 UTC
There seems to be a race condition occuring in release_pool_engine. When I run the example code below (JPL), the program seems to lock up in about 1 of 3 runs. 

Because this seems an issue with a race condition, I suppose the computer speed and processor details like number of cores and caching makes a difference on how reproducable this will be. 

SWI 7.4.2 

Windows 8.1 Enterprise, 64 bit, Intel Core(TM) i5-4900 @ 3.3GHz
8GB RAM

Java  version 1.8.0_112
Java SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-bit server VM (build 25.112-b15, mixed mode)

I'm running the test code inside Eclipse Oxygen 4.7.0 and we also install both SWI and JPL on the fly in a temp directory automatically. I suppose that all makes no difference but we may have to dig deeper if you can't reproduce this.

```
	@Test
	public void multiThreadTest() throws InterruptedException {
		System.out.println("Multi-thread test with simple query");
		List<Thread> threads = new ArrayList<>();
		for (int n = 0; n < 200; n++) {
			threads.add(runSimpleThread(n));
		}
		while (!threads.isEmpty()) {
			Thread thread = threads.get(0);
			// System.out.println("Waiting for " + thread);
			thread.join();
			threads.remove(thread);
		}
	}
	
	private Thread runSimpleThread(final int n) {
		Thread thread = new Thread(new Runnable() {
			@Override
			public void run() {
				new Query("between(1,1000000,I),fail").allSolutions();
			}
		});
		thread.start();
		return thread;
	}

```

**Comment by Wouter1** [comment] 2017-07-31 12:37
BTW the same test code runs fine on 32 bit Windows and on OSX.

**Comment by JanWielemaker** [comment] 2017-07-31 12:48
As I know virtually nothing about Java, please create something I can run using `javac` and `java` from the command line.

**Comment by Wouter1** [comment] 2017-07-31 13:22
Thanks for the quick response. I'll look into converting this to a simple java program.

**Comment by Wouter1** [comment] 2017-07-31 14:21
@JanWielemaker  Here is the program with instructions how to build and run it 
Notice that I modified the program a little, to make it better reproducable on a much faster Alienware on Windows10 64 bit on Java 1.8.0_144. Here it hangs about 1 in 3 runs now.



```

/**
* compile with: javac -classpath ".;C:\Program Files\swipl\lib\jpl.jar" test.java
* set PATH=C:\Program Files\swipl\bin;%PATH%
* run with: java -classpath ".;C:\Program Files\swipl\lib\jpl.jar" -Djava.library.path="C:\Program Files\swipl\bin" test
*/

import java.util.ArrayList;
import java.util.List;

import org.jpl7.Query;

public class test {

	private static Thread runSimpleThread(final int n) {
		Thread thread = new Thread(new Runnable() {
			@Override
			public void run() {
				new Query("between(1,1000,I),fail").allSolutions();
			}
		});
		thread.start();
		return thread;
	}

	public static void main(String[] args) throws InterruptedException {
		System.out.println("Multi-thread test with simple query");
		List<Thread> threads = new ArrayList<>();
		for (int n = 0; n < 2000; n++) {
			threads.add(runSimpleThread(n));
		}
		while (!threads.isEmpty()) {
			Thread thread = threads.get(0);
			// System.out.println("Waiting for " + thread);
			thread.join();
			threads.remove(thread);
		}

	}
}
```

**Comment by Wouter1** [comment] 2017-07-31 14:24
BTW put that text in a file called "test.java" and do "cd" to the directory containing the test.java file before executing the compile and run commands

**Comment by Wouter1** [comment] 2017-07-31 14:38
BTW2 the problem might exist on Win32 as well, I had a deadlock there one time but it did not reproduce at that time.

**Comment by JanWielemaker** [comment] 2017-07-31 15:04
Got it running, but it works just fine (Ubuntu Linux).   Now this could already be fixed in 7.5.x.  Most valuable is of course some indication on what is waiting for what using a C debugger ...

**Comment by Wouter1** [comment] 2017-07-31 17:51
@JanWielemaker  Great that you got  the test working!

Good that it works fine on Linux. I didn't test there yet, but we are also going to port our stuff to Linux (probably tomorrow0.

FAIK the issue I found only occurs on Windows.  Can you test that to see if it reproduces with you?

**Comment by Wouter1** [comment] 2017-08-29 07:14
@JanWielemaker  I did get a confirmation that the bug also reproduces on Win32.

Do you have an update on the status of this issue?

**Comment by JanWielemaker** [comment] 2017-08-30 08:31
Are we still talking 7.4.x or the latest development versions?   So many things have been changed to the locking that this might be fixed as a result.   I'm not going to debug old versions.

**Comment by Wouter1** [comment] 2017-08-30 08:42
@JanWielemaker  Let's concentrate about the versions where you do the tests and do the fixes. 

Are you still fixing 7.4 as well?

**Comment by JanWielemaker** [comment] 2017-08-30 08:54
Fine.  That doesn't really answer my question though: can you reproduce this using the latest development versions?  I don't have a physical Windows machine and only a very old Win7 VM.  If it still reproduces I'll try to get people with more Windows experience involved.

And no, 7.4 won't be fixed for this.  Hope 7.6 arrives shortly but we are trying to improve several things that appear more complicated than we feared :(

**Comment by Wouter1** [comment] 2017-08-30 09:02
@JanWielemaker  Euh, I'm not aware that you asked that question?

But to answer your question, yes a collegue  reproduced this last week with SWI Prolog develop DLLs (7.5.13) on Win32

I suppose it will reproduce also on a Win7 VM.

> Hope 7.6 arrives shortly

It would be great if it could incorporate a fix for the current issue as well, then we could use a stable version in our system.

>more complicated than we feared
Sounds like a recipe for a headache. Good luck!

**Comment by JanWielemaker** [comment] 2017-08-30 09:05
I did:

> Are we still talking 7.4.x or the latest development versions?

Anyway, I'll try to get this on the agenda.  No promises though ...

**Comment by Wouter1** [comment] 2017-08-30 09:25
@JanWielemaker  

ok.

It was not clear from that question that you wanted to  know about test results. I thought you were wondering which version we would like to see fixed.

**Comment by JanWielemaker** [comment] 2017-08-30 15:22
Got that reproduced (after reinstalling Java, etc :().  The trouble was most likely in `pthread-win32`, emulating POSIX thread primitives on Windows.  Completed Prolog threads remain blocked in
`pthread_cond_signal()`, which should never block.   I've replaced the engine pool in `jpl.c` with
Windows Events, which are much simpler,  but good enough for this purpose.  Using that the
test ran fine for 200 times while using the old code it hang about once every five runs.

Should be in tomorrows daily downloads.   Please test and close if you agree.  You might be able to use the new JPL with 7.4.2. Do replace jpl.dll, jpl.jar and jpl.pl in that case.  Not tested.

See SWI-Prolog/packages-jpl@9fc80d64a751c45041c79e3b516c62efc3b18421

**Comment by JanWielemaker** [comment] 2017-08-30 19:12
Cycling home made we worry a bit more.  It turns out the pool management code doesn't lock the mutex before calling `pthread_cond_signal()`.  I think that is allowed, but inherently dangerous as it can loose the signal, causing a deadlock.  Given that we should loose multiple signals before any real harm is done this is not very likely, but still ...

Adding the lock also fixes the deadlock for Windows.  In other words, the `pthread-win32` pthread_cond_signal() seems fine if you hold the associated mutex.  This may not follow the strict POSIX standard, but can be defended as not holding the mutex is (almost?) always wrong. Still maintained an Event/CriticalSection implementation for Windows as this can be fairly time critical and `pthread-win32` condition variables are not very fast.

See SWI-Prolog/packages-jpl@c468c1cfb1621d7fbb82b5e79f6197d052a1642d

**Comment by Venorcis** [comment] 2017-08-31 06:02
Hello Jan, I'm one of Wouter's colleagues. I just tried out running JPL from the nightly build on SWI 7.4.2 on Windows 32-bits (replacing the 3 files you indicated), and that seems to work! I'm not encountering any deadlocks in our multi-thread test anymore 👍 

However, I am getting some ACCES_VIOLATION exceptions in our GOAL agents now: "org.jpl7.fli.Prolog.get_string_chars(Lorg/jpl7/fli/term_t;Lorg/jpl7/fli/StringHolder;)Z+0"

Tried switching to the nightly build all together. Different error (GUARD_PAGE) but at the same place: "org.jpl7.fli.Prolog.get_string_chars(Lorg/jpl7/fli/term_t;Lorg/jpl7/fli/StringHolder;)Z+0". This C function is called from "org.jpl7.Term.getTerm(Ljava/util/Map;Lorg/jpl7/fli/term_t;)Lorg/jpl7/Term" in both instances.

**Comment by Venorcis** [comment] 2017-08-31 06:57
I reproduced the issue in the test given here as well just by running it for a longer time. Again an EXCEPTION_ACCESS_VIOLATION:
```
J 140  org.jpl7.fli.Prolog.cons_functor_v(Lorg/jpl7/fli/term_t;Lorg/jpl7/fli/functor_t;Lorg/jpl7/fli/term_t;)V (0 bytes) @ 0x026b8c5d [0x026b8be0+0x7d]
J 163 C1 org.jpl7.Atom.put(Ljava/util/Map;Lorg/jpl7/fli/term_t;)V (44 bytes) @ 0x026eb3a0 [0x026eb290+0x110]
J 109 C1 org.jpl7.Term.putTerms(Ljava/util/Map;[Lorg/jpl7/Term;)Lorg/jpl7/fli/term_t; (58 bytes) @ 0x026dfacc [0x026dfa20+0xac]
J 155 C1 org.jpl7.Query.open()V (250 bytes) @ 0x026e98e4 [0x026e9690+0x254]
J 217 C1 org.jpl7.Util.textToTerm(Ljava/lang/String;)Lorg/jpl7/Term; (87 bytes) @ 0x026f917c [0x026f8e50+0x32c]
```

(and again possibly unrelated 'internal exceptions')
```
Event: 0.028 Thread 0x00fccc00 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x04606e98) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u131\8869\hotspot\src\share
Event: 0.028 Thread 0x00fccc00 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x04607168) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp,
Event: 0.176 Thread 0x00fccc00 Exception <a 'java/security/PrivilegedActionException'> (0x04930198) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.176 Thread 0x00fccc00 Exception <a 'java/security/PrivilegedActionException'> (0x049305d8) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.176 Thread 0x00fccc00 Exception <a 'java/security/PrivilegedActionException'> (0x049347d0) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.176 Thread 0x00fccc00 Exception <a 'java/security/PrivilegedActionException'> (0x04934bb0) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
```

**Comment by JanWielemaker** [comment] 2017-08-31 08:05
Hard to tell.  Quite surely unrelated to these recent patches.  I don't know whether the 7.5 JPL is fully binary compatible with 7.4.  This is surely an indication that it might not be.  Use the daily for the whole job or backport these patches to JPL as it was in 7.4 and recompile that.  If the problem persists, make a new issue (adding a program to reproduce).  I close this issue as I'm quite convinced this is gone.

**Closed by JanWielemaker** 2017-08-31 08:05 UTC

**Comment by Venorcis** [comment] 2017-08-31 08:13
I got the issue running the same sample as provided here with both using the full daily build or 7.4.2 with only the JPL updated; it didn't seem to matter. It is way less frequent than the deadlock but still seems to be a multi-threading issue in JPL. Moreover, if pthread signals are bugged in Windows it is not a far stretch that the mutex locking/unlocking might be bugged either, i.e., as used in the jpl_ensure_jpl_init and jpl_ensure_pvm_init functions (ánd jpl_ensure_pvm_init is a common factor between the two different locations I got the access violation at).

I'd be happy to create a new issue, but again the code used to reproduce it is the same, just running it longer as the exception seems rarer.

**Comment by JanWielemaker** [comment] 2017-08-31 08:50
It is still a different issue.  I've ran the code in a loop for 1,000 times and did that a number of times during the debugging.  Didn't see any access violations.  This was using Windows 7 running Oracle jre 1.8.0_144 Java.

And no, as I explained above, it only turns out pthread_cond_signal() does require the associated lock to be held.  This is generally a good idea (read needed) anyway, but on most implementations pthread_cond_signal() itself doesn't require this.  So, there is no indication of issues with pthread-win32, only some limitations.

Please start a new issue as this is definitely not the same deadlock issue.  You can copy the code.  I fear you need to give more indications on how to reproduce this, unless running it a couple of thousands of times is not enough in general.
