### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION in multi-threaded JPL

### ISSUE THREAD

**Issue by Venorcis** [SWI-Prolog/issues#60] opened 2017-08-31 13:48 UTC
Consider the following example program:
```
/**
* compile with: javac -classpath ".;C:\Program Files (x86)\swipl\lib\jpl.jar" test.java
* set PATH=C:\Program Files (x86)\swipl\bin;%PATH%
* run with: java -classpath ".;C:\Program Files (x86)\swipl\lib\jpl.jar" -Djava.library.path="C:\Program Files (x86)\swipl\bin" test
*/

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import org.jpl7.Query;

public class test {
	public static void main(String[] args) throws Exception {
		List<Thread> threads = new ArrayList<>(10);
		for (int n = 0; n < 10; n++) {
			threads.add(runThreadInsertDelete(n));
		}
		while (!threads.isEmpty()) {
			Thread thread = threads.get(0);
			thread.join();
			threads.remove(thread);
		}
	}

	private static Thread runThreadInsertDelete(final int n) {
		Thread thread = new Thread(new Runnable() {
			@Override
			public void run() {
				try {
					testInsertDelete(n);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
		thread.start();
		return thread;
	}

	private static void testInsertDelete(int n) throws Exception {
		Random r = new Random();
		long endTime = System.currentTimeMillis() + 600000;
		while (System.currentTimeMillis() < endTime) {
			double random = r.nextInt();
			new Query("assert(r(" + random + "))").allSolutions();
			new Query("retract(r(" + random + "))").allSolutions();
		}
	}
}
```

Depending on the hardware, this program will run under a constantly increasing amount of memory, until at a certain point (on my machine after several minutes) an EXCEPTION_ACCESS_VIOLATION is generated:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x6d489be4, pid=6704, tid=0x000014c8
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) Client VM (25.131-b11 mixed mode windows-x86 )
# Problematic frame:
# C  [libswipl.dll+0x9be4]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x156d3800):  JavaThread "Thread-9" [_thread_in_native, id=5320, stack(0x168e0000,0x16930000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x8c001708

Registers:
EAX=0x8c001700, EBX=0x1620fe10, ECX=0x013bb000, EDX=0x0000001f
ESP=0x1692f5d0, EBP=0x00000000, ESI=0x00000000, EDI=0x00000018
EIP=0x6d489be4, EFLAGS=0x00010206

Top of Stack: (sp=0x1692f5d0)
0x1692f5d0:   00000021 156d3940 1692f660 00000022
0x1692f5e0:   13a24da7 00000018 00000018 156d3940
0x1692f5f0:   1692f5e0 156bb120 1692fa5c 156d3940
0x1692f600:   00000018 0000000d 1692f658 6bd87d59
0x1692f610:   00000018 0000000d 0000001b 00000000
0x1692f620:   00000000 1692f64c 156d3800 03081aa1
0x1692f630:   156d3940 1692f64c 1692f644 1692f648
0x1692f640:   1692f660 051230f0 05123120 0a550a88 

Instructions: (pc=0x6d489be4)
0x6d489bc4:   eb 81 c1 ed 0c b8 af 02 00 00 8b 7c 24 14 0f bd
0x6d489bd4:   d5 83 f2 1f 29 d0 8b 04 85 64 e5 57 6d 8b 04 a8
0x6d489be4:   8b 50 08 8b 43 1c 89 14 b8 83 c4 2c b8 01 00 00
0x6d489bf4:   00 5b 5e 5f 5d c3 8d 56 01 c7 44 24 04 01 00 00 


Register to memory mapping:

EAX=0x8c001700 is an unknown value
EBX=0x1620fe10 is an unknown value
ECX=0x013bb000 is an unknown value
EDX=0x0000001f is an unknown value
ESP=0x1692f5d0 is pointing into the stack for thread: 0x156d3800
EBP=0x00000000 is an unknown value
ESI=0x00000000 is an unknown value
EDI=0x00000018 is an unknown value


Stack: [0x168e0000,0x16930000],  sp=0x1692f5d0,  free space=317k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libswipl.dll+0x9be4]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 87  org.jpl7.fli.Prolog.cons_functor_v(Lorg/jpl7/fli/term_t;Lorg/jpl7/fli/functor_t;Lorg/jpl7/fli/term_t;)V (0 bytes) @ 0x03081a5d [0x030819e0+0x7d]
J 117 C1 org.jpl7.Atom.put(Ljava/util/Map;Lorg/jpl7/fli/term_t;)V (44 bytes) @ 0x03087be0 [0x03087ad0+0x110]
J 35 C1 org.jpl7.Term.putTerms(Ljava/util/Map;[Lorg/jpl7/Term;)Lorg/jpl7/fli/term_t; (58 bytes) @ 0x03072f0c [0x03072e60+0xac]
J 68 C1 org.jpl7.Query.open()V (250 bytes) @ 0x0307ce24 [0x0307cbd0+0x254]
J 137 C1 org.jpl7.Util.textToTerm(Ljava/lang/String;)Lorg/jpl7/Term; (87 bytes) @ 0x0309047c [0x03090150+0x32c]
J 146% C1 test.testInsertDelete(I)V (101 bytes) @ 0x030924f0 [0x030921e0+0x310]
j  test.access$0(I)V+1
j  test$1.run()V+4
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
=>0x156d3800 JavaThread "Thread-9" [_thread_in_native, id=5320, stack(0x168e0000,0x16930000)]
  0x156d2400 JavaThread "Thread-8" [_thread_in_native, id=13584, stack(0x16850000,0x168a0000)]
  0x156d0400 JavaThread "Thread-7" [_thread_in_native, id=11976, stack(0x167c0000,0x16810000)]
  0x156c9800 JavaThread "Thread-6" [_thread_in_native, id=3516, stack(0x16730000,0x16780000)]
  0x156c1800 JavaThread "Thread-5" [_thread_in_native, id=7116, stack(0x166a0000,0x166f0000)]
  0x156c0800 JavaThread "Thread-4" [_thread_in_native, id=10644, stack(0x16610000,0x16660000)]
  0x156bd000 JavaThread "Thread-3" [_thread_in_native, id=5716, stack(0x16580000,0x165d0000)]
  0x156ba000 JavaThread "Thread-2" [_thread_in_native, id=2756, stack(0x164f0000,0x16540000)]
  0x156b4400 JavaThread "Thread-1" [_thread_in_native, id=13328, stack(0x16460000,0x164b0000)]
  0x156b3c00 JavaThread "Thread-0" [_thread_in_native, id=12228, stack(0x163d0000,0x16420000)]
  0x155ef000 JavaThread "Service Thread" daemon [_thread_blocked, id=12584, stack(0x15ba0000,0x15bf0000)]
  0x155c5000 JavaThread "C1 CompilerThread0" daemon [_thread_blocked, id=2252, stack(0x15b10000,0x15b60000)]
  0x155ce800 JavaThread "Attach Listener" daemon [_thread_blocked, id=1368, stack(0x15a80000,0x15ad0000)]
  0x155cd800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=14148, stack(0x159f0000,0x15a40000)]
  0x155b9c00 JavaThread "Finalizer" daemon [_thread_blocked, id=12528, stack(0x15870000,0x158c0000)]
  0x155a3c00 JavaThread "Reference Handler" daemon [_thread_blocked, id=10924, stack(0x157e0000,0x15830000)]
  0x02fbc800 JavaThread "main" [_thread_blocked, id=3780, stack(0x01600000,0x01650000)]

Other Threads:
  0x02f9c800 VMThread [stack: 0x15550000,0x155a0000] [id=8656]
  0x155fb400 WatcherThread [stack: 0x15c30000,0x15c80000] [id=4824]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 def new generation   total 4928K, used 1174K [0x05000000, 0x05550000, 0x0a550000)
  eden space 4416K,  26% used [0x05000000, 0x05124d28, 0x05450000)
  from space 512K,   0% used [0x05450000, 0x05450c38, 0x054d0000)
  to   space 512K,   0% used [0x054d0000, 0x054d0000, 0x05550000)
 tenured generation   total 10944K, used 386K [0x0a550000, 0x0b000000, 0x15000000)
   the space 10944K,   3% used [0x0a550000, 0x0a5b0a20, 0x0a5b0c00, 0x0b000000)
 Metaspace       used 2119K, capacity 2344K, committed 2368K, reserved 4480K

Card table byte_map: [0x15000000,0x15090000] byte_map_base: 0x14fd8000

Polling page: 0x011b0000

CodeCache: size=32768Kb used=844Kb max_used=844Kb free=31923Kb
 bounds [0x02fc0000, 0x03098000, 0x04fc0000]
 total_blobs=291 nmethods=146 adapters=76
 compilation: enabled

Compilation events (10 events):
Event: 0.236 Thread 0x155c5000  142             java.util.concurrent.atomic.AtomicLong::get (5 bytes)
Event: 0.236 Thread 0x155c5000 nmethod 142 0x03091708 code [0x03091800, 0x03091890]
Event: 0.237 Thread 0x155c5000  143             java.util.concurrent.atomic.AtomicLong::compareAndSet (13 bytes)
Event: 0.237 Thread 0x155c5000 nmethod 143 0x030918c8 code [0x030919c0, 0x03091a70]
Event: 0.247 Thread 0x155c5000  144             java.util.Random::next (47 bytes)
Event: 0.247 Thread 0x155c5000 nmethod 144 0x03091ac8 code [0x03091bc0, 0x03091d00]
Event: 0.248 Thread 0x155c5000  145             java.util.Random::nextInt (7 bytes)
Event: 0.248 Thread 0x155c5000 nmethod 145 0x03091dc8 code [0x03091ec0, 0x03091f5c]
Event: 0.578 Thread 0x155c5000  146 %           test::testInsertDelete @ 19 (101 bytes)
Event: 0.579 Thread 0x155c5000 nmethod 146% 0x03091fc8 code [0x030921e0, 0x03092958]

GC Heap History (10 events):
Event: 175.566 GC heap before
{Heap before GC invocations=453 (full 0):
 def new generation   total 4928K, used 4419K [0x05000000, 0x05550000, 0x0a550000)
  eden space 4416K, 100% used [0x05000000, 0x05450000, 0x05450000)
  from space 512K,   0% used [0x054d0000, 0x054d0de8, 0x05550000)
  to   space 512K,   0% used [0x05450000, 0x05450000, 0x054d0000)
 tenured generation   total 10944K, used 386K [0x0a550000, 0x0b000000, 0x15000000)
   the space 10944K,   3% used [0x0a550000, 0x0a5b0a20, 0x0a5b0c00, 0x0b000000)
 Metaspace       used 2119K, capacity 2344K, committed 2368K, reserved 4480K
Event: 175.567 GC heap after
Heap after GC invocations=454 (full 0):
 def new generation   total 4928K, used 2K [0x05000000, 0x05550000, 0x0a550000)
  eden space 4416K,   0% used [0x05000000, 0x05000000, 0x05450000)
  from space 512K,   0% used [0x05450000, 0x05450b70, 0x054d0000)
  to   space 512K,   0% used [0x054d0000, 0x054d0000, 0x05550000)
 tenured generation   total 10944K, used 386K [0x0a550000, 0x0b000000, 0x15000000)
   the space 10944K,   3% used [0x0a550000, 0x0a5b0a20, 0x0a5b0c00, 0x0b000000)
 Metaspace       used 2119K, capacity 2344K, committed 2368K, reserved 4480K
}
Event: 176.755 GC heap before
{Heap before GC invocations=454 (full 0):
 def new generation   total 4928K, used 4418K [0x05000000, 0x05550000, 0x0a550000)
  eden space 4416K, 100% used [0x05000000, 0x05450000, 0x05450000)
  from space 512K,   0% used [0x05450000, 0x05450b70, 0x054d0000)
  to   space 512K,   0% used [0x054d0000, 0x054d0000, 0x05550000)
 tenured generation   total 10944K, used 386K [0x0a550000, 0x0b000000, 0x15000000)
   the space 10944K,   3% used [0x0a550000, 0x0a5b0a20, 0x0a5b0c00, 0x0b000000)
 Metaspace       used 2119K, capacity 2344K, committed 2368K, reserved 4480K
Event: 176.755 GC heap after
Heap after GC invocations=455 (full 0):
 def new generation   total 4928K, used 3K [0x05000000, 0x05550000, 0x0a550000)
  eden space 4416K,   0% used [0x05000000, 0x05000000, 0x05450000)
  from space 512K,   0% used [0x054d0000, 0x054d0c38, 0x05550000)
  to   space 512K,   0% used [0x05450000, 0x05450000, 0x054d0000)
 tenured generation   total 10944K, used 386K [0x0a550000, 0x0b000000, 0x15000000)
   the space 10944K,   3% used [0x0a550000, 0x0a5b0a20, 0x0a5b0c00, 0x0b000000)
 Metaspace       used 2119K, capacity 2344K, committed 2368K, reserved 4480K
}
Event: 178.393 GC heap before
{Heap before GC invocations=455 (full 0):
 def new generation   total 4928K, used 4419K [0x05000000, 0x05550000, 0x0a550000)
  eden space 4416K, 100% used [0x05000000, 0x05450000, 0x05450000)
  from space 512K,   0% used [0x054d0000, 0x054d0c38, 0x05550000)
  to   space 512K,   0% used [0x05450000, 0x05450000, 0x054d0000)
 tenured generation   total 10944K, used 386K [0x0a550000, 0x0b000000, 0x15000000)
   the space 10944K,   3% used [0x0a550000, 0x0a5b0a20, 0x0a5b0c00, 0x0b000000)
 Metaspace       used 2119K, capacity 2344K, committed 2368K, reserved 4480K
Event: 178.394 GC heap after
Heap after GC invocations=456 (full 0):
 def new generation   total 4928K, used 3K [0x05000000, 0x05550000, 0x0a550000)
  eden space 4416K,   0% used [0x05000000, 0x05000000, 0x05450000)
  from space 512K,   0% used [0x05450000, 0x05450cb8, 0x054d0000)
  to   space 512K,   0% used [0x054d0000, 0x054d0000, 0x05550000)
 tenured generation   total 10944K, used 386K [0x0a550000, 0x0b000000, 0x15000000)
   the space 10944K,   3% used [0x0a550000, 0x0a5b0a20, 0x0a5b0c00, 0x0b000000)
 Metaspace       used 2119K, capacity 2344K, committed 2368K, reserved 4480K
}
Event: 180.064 GC heap before
{Heap before GC invocations=456 (full 0):
 def new generation   total 4928K, used 4419K [0x05000000, 0x05550000, 0x0a550000)
  eden space 4416K, 100% used [0x05000000, 0x05450000, 0x05450000)
  from space 512K,   0% used [0x05450000, 0x05450cb8, 0x054d0000)
  to   space 512K,   0% used [0x054d0000, 0x054d0000, 0x05550000)
 tenured generation   total 10944K, used 386K [0x0a550000, 0x0b000000, 0x15000000)
   the space 10944K,   3% used [0x0a550000, 0x0a5b0a20, 0x0a5b0c00, 0x0b000000)
 Metaspace       used 2119K, capacity 2344K, committed 2368K, reserved 4480K
Event: 180.065 GC heap after
Heap after GC invocations=457 (full 0):
 def new generation   total 4928K, used 3K [0x05000000, 0x05550000, 0x0a550000)
  eden space 4416K,   0% used [0x05000000, 0x05000000, 0x05450000)
  from space 512K,   0% used [0x054d0000, 0x054d0d98, 0x05550000)
  to   space 512K,   0% used [0x05450000, 0x05450000, 0x054d0000)
 tenured generation   total 10944K, used 386K [0x0a550000, 0x0b000000, 0x15000000)
   the space 10944K,   3% used [0x0a550000, 0x0a5b0a20, 0x0a5b0c00, 0x0b000000)
 Metaspace       used 2119K, capacity 2344K, committed 2368K, reserved 4480K
}
Event: 181.398 GC heap before
{Heap before GC invocations=457 (full 0):
 def new generation   total 4928K, used 4419K [0x05000000, 0x05550000, 0x0a550000)
  eden space 4416K, 100% used [0x05000000, 0x05450000, 0x05450000)
  from space 512K,   0% used [0x054d0000, 0x054d0d98, 0x05550000)
  to   space 512K,   0% used [0x05450000, 0x05450000, 0x054d0000)
 tenured generation   total 10944K, used 386K [0x0a550000, 0x0b000000, 0x15000000)
   the space 10944K,   3% used [0x0a550000, 0x0a5b0a20, 0x0a5b0c00, 0x0b000000)
 Metaspace       used 2119K, capacity 2344K, committed 2368K, reserved 4480K
Event: 181.399 GC heap after
Heap after GC invocations=458 (full 0):
 def new generation   total 4928K, used 3K [0x05000000, 0x05550000, 0x0a550000)
  eden space 4416K,   0% used [0x05000000, 0x05000000, 0x05450000)
  from space 512K,   0% used [0x05450000, 0x05450c38, 0x054d0000)
  to   space 512K,   0% used [0x054d0000, 0x054d0000, 0x05550000)
 tenured generation   total 10944K, used 386K [0x0a550000, 0x0b000000, 0x15000000)
   the space 10944K,   3% used [0x0a550000, 0x0a5b0a20, 0x0a5b0c00, 0x0b000000)
 Metaspace       used 2119K, capacity 2344K, committed 2368K, reserved 4480K
}

Deoptimization events (0 events):
No events

Internal exceptions (2 events):
Event: 0.034 Thread 0x02fbc800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x05006e98) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u131\8869\hotspot\src\share
Event: 0.035 Thread 0x02fbc800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x05007168) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u131\8869\hotspot\src\share\vm\prims\jni.cpp,

Events (10 events):
Event: 175.566 Executing VM operation: GenCollectForAllocation
Event: 175.567 Executing VM operation: GenCollectForAllocation done
Event: 176.755 Executing VM operation: GenCollectForAllocation
Event: 176.755 Executing VM operation: GenCollectForAllocation done
Event: 178.393 Executing VM operation: GenCollectForAllocation
Event: 178.394 Executing VM operation: GenCollectForAllocation done
Event: 180.064 Executing VM operation: GenCollectForAllocation
Event: 180.065 Executing VM operation: GenCollectForAllocation done
Event: 181.395 Executing VM operation: GenCollectForAllocation
Event: 181.399 Executing VM operation: GenCollectForAllocation done


---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 15063 (10.0.15063.296)

CPU:total 8 (initial active 8) (4 cores per cpu, 2 threads per core) family 6 model 60 stepping 3, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2

Memory: 4k page, physical 16677952k(8888112k free), swap 17726528k(7820120k free)

vm_info: Java HotSpot(TM) Client VM (25.131-b11) for windows-x86 JRE (1.8.0_131-b11), built on Mar 15 2017 01:26:29 by "java_re" with MS VC++ 10.0 (VS2010)

time: Thu Aug 31 15:44:32 2017
elapsed time: 181 seconds (0d 0h 3m 1s)
```

This behaviour occurs with the latest SWI nightly build, SWI 7.4.2 with an updated jpl.dll (to fix the deadlock issue), and even SWI 6.0.2

**Comment by JanWielemaker** [comment] 2017-09-01 08:27
After a small extension to control the runtime and dump the first N functors I tested with this program.
[t3.zip](https://github.com/SWI-Prolog/issues/files/1269605/t3.zip)

That emits zillions of functors like this:

```
assert(r(-3.38680072E8))/0
retract(r(1.973383717E9))/0
assert(r(1.352000435E9))/0
assert(r(5.63008113E8))/0
assert(r(-2.072127018E9))/0
retract(r(5.42541275E8))/0
retract(r(-1.596975294E9))/0
retract(r(-2.010044488E9))/0
```

So it appears every goal at some point is a functor with arity 0.  Such beasts are not garbage collected and therefore you run out of memory.  This is not a SWI-Prolog bug.  I somehow recall this is an issue with JPL, but I know little of its internals.  I'll point Paul at this issue.

This issue should be moved to packages-jpl, but that is not available on Github :-1:

**Comment by Venorcis** [comment] 2017-09-01 09:24
Thanks for investigating Jan. I do have to note that with our GOAL agents the access violation occurs quite rapidly sometimes, so it doesn't necessarily seem related to running out of memory. Moreover, making sure that all jpl.Query solution calls are done under a lock (i.e. single-threaded) resolves all of these issues. Both suggest to me some race condition (possibly with garbage collection?) is occurring (in JPL?).

**Comment by JanWielemaker** [comment] 2017-09-01 10:03
SWI-Prolog's threading support has evolved a lot, in particular over the last year.  Notably the deployment of SWISH has been an important factor here.   Unfortunately, linking with Java doesn't make this easier.  On Unix systems there is a fight about signal handling.  This is now mostly resolves as SWI-Prolog no longer really needs to do signal handling.  The JPL API relies on the engine pool interface which is not used for much else AFAIK and thus not much stress tested.  Finally, if something crashes it is really hard to debug in the combined Java/Prolog binary, especially on Windows.

If you want to help making this better, please send in programs as you did.  The program in this issue is a perfect example.  Nice, small and reproducible.   The issue is not at all related to threading but to misusing the Prolog API. Please raise issues at the packages-jpl repo.

**Comment by anionic** [comment] 2017-09-01 19:57
The functor leak seems to be in a convenience method which you are (indirectly) using to construct your goals as org.jpl7.Term instances from strings in Prolog source syntax. I will investigate further. A workaround for your example is to replace
```
new Query("assert(r(" + random + "))").allSolutions();
new Query("retract(r(" + random + "))").allSolutions();
```
by e.g.
```
Term clause = new Compound("r", new Term[] {new Float(random)});
new Query("assert", clause).allSolutions();
new Query("retract", clause).allSolutions();
```

**Comment by Venorcis** [comment] 2017-09-01 20:33
@anionic thanks for investigating. We actually use the Query constructor that takes a single Term (which is an instantiated Compound of assert/retract with some content similar to your example above) in our agents but that still seems to end in access violations (but again only in multi-threaded use of Query.allSolutions; using a lock for just calling resolves all issues though with a significant performance impact).

**Comment by JanWielemaker** [comment] 2017-09-02 07:22
After the proposed change, your example runs robust on Ubuntu using 7.5.14 without locks (on 8 cores). Only the VM instructions admin seems broken as the number of VM instructions gets negative :(  That statistics isn't used for anything though.   New test case please :+1:

**Comment by JanWielemaker** [comment] 2017-09-04 12:34
The leak caused by `new Query("assert(r(" + random + "))").allSolutions();` was due to a cleanup that reverted a patch for this.  Re-applied and the string based version runs fine again.  I'd assume that
the string based version is slower though as well as subject to injection issues if the string comes from outside.  I close this one now.  Please create a new issue with `packages-jpl` if you find new (concurrency) issues.

**Closed by JanWielemaker** 2017-09-04 12:34 UTC

**Comment by Venorcis** [comment] 2017-09-05 14:33
Thanks gentlemen, this fix with the earlier threading improvements (and the deadlock fix) seems to have resolved all our issues for the moment, great!
