### ISSUE TITLE
No permission to load source "...lists.pl"

### ISSUE THREAD

**Issue by Wouter1** [SWI-Prolog/issues#40] opened 2016-05-11 11:42 UTC
Compiled latest SWI 7.2.3 from sources and installed. 

SWI runs fine
```
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.2.3)
...
```

Test machine: 
```
Processor  2.93 GHz Intel Core i7
Memory  4 GB 1333 MHz DDR3
Graphics  ATI Radeon HD 5750 1024 MB
Software  OS X 10.9.5 (13F1712)
```

We checked that simple JPL tests run fine.

Then we change the Zahed.java example to contain the following
```
import java.util.Map;

import org.jpl7.Atom;
import org.jpl7.Compound;
import org.jpl7.Query;
import org.jpl7.Term;
import org.jpl7.Variable;
import org.jpl7.JPL;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class Zahed {
	private static final int NTHREADS = 88;
	private static final String SwiPath ="/usr/lib/swipl-6.2.3/"; 

	public static void main(java.lang.String argv[]) throws InterruptedException {
	JPL.setDefaultInitArgs(new String[] { "--quiet", "--nosignals" });
	JPL.setDTMMode(false);
		new Zahed().multiThreadTest();
	}

	public void multiThreadTest() throws InterruptedException {
		System.out.println("Multi-thread test");
		List<Thread> threads = new ArrayList<Thread>();
		for (int n = 0; n < NTHREADS; n++) {
			threads.add(runThread(n));
		}
		while (!threads.isEmpty()) {
			Thread thread = threads.get(0);
			// System.out.println("Waiting for " + thread);
			thread.join();
			threads.remove(thread);
		}
	}

	private Thread runThread(final int n) {
		Thread thread = new Thread(new Runnable() {
			@Override
			public void run() {
				try {
					testSimpleQueries(n);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		});
		thread.start();
		return thread;
	}

	private void testSimpleQueries(int n) throws InterruptedException {
		new Query("set_prolog_flag(debug_on_error,false)").hasSolution();

		String module = "robot_" + n;
		String formula = "test :- member(3,[1,2,3,4,5])";
		insert(module, formula);
		Map<String, Term> res = query(module, "test");

		insert(module, "fibo(0,0)");
		insert(module, "fibo(1,0)");
		insert(module,
				"fibo(X,Y):-X>1, X1 is X-1, X2 is X-2, fibo(X1,Y1), fibo(X2,Y2), Y is Y1 + Y2");
		query(module, "listing");

		res = query(module, "fibo(22,Y)");
	}

	private void insert(String module, String formula) {
		String f = "assert(" + module + ":(" + formula + "))";
		// System.out.println(f);
		new Query(f).hasSolution();
	}

	@SuppressWarnings("unchecked")
	private Map<String, Term> query(String module, String formula) {
		String q = module + ":" + formula;
		// System.out.println(q);
		return new Query(q).allSolutions()[0];
	}
}
```

we run it . We get many exceptions like this
```
ERROR: Unhandled exception: load_files/2: No permission to load source `'/usr/lib/swipl-7.2.3/library/lists.pl'' (Non-module file already loaded into module robot_36; trying to load into robot_61)
```

**Comment by JanWielemaker** [comment] 2016-05-11 11:54
You probably better try the mailinglist to get feedback.   I have some remarks:

  - The code says `"/usr/lib/swipl-6.2.3/"`.  Inconsistent version?
  - Does it run with one thread?
  - Concurrency of 7.3 is much better
  - I think JPL only runs a quite limited number of tasks concurrently anyway.  I'm not that
    familiar with JPL though.

**Comment by Wouter1** [comment] 2016-05-11 12:17
Thanks Jan 

>The code says "/usr/lib/swipl-6.2.3/". Inconsistent version?

Sorry, that's some left-over unused variable from something else I tried. I should have removed that line. 

>Does it run with one thread?

Yes it did on my machine that runs swi 6. I did not try on 7.2.3

>Concurrency of 7.3 is much better

But that is the develop version? Do you want us to test that version?

>I think JPL only runs a quite limited number of tasks concurrently anyway. I'm not that familiar with JPL though.
>I think JPL only runs a quite limited number of tasks concurrently anyway. I'm not that familiar with JPL though.
I believe this is a bug, not something to get feedback. Where should I post this bug?

**Comment by JanWielemaker** [comment] 2016-05-11 12:31
> But that is the develop version? Do you want us to test that version?

Might be a good idea.  Its different concurrency design fixes at least a possible conflict in signal handling between Java and Prolog on Unix systems.

> I believe this is a bug, not something to get feedback. Where should I post this bug?

The mailinglist is a good place for bugs, in particular if it is not that clear where the bug might be.
You might also want to have a look at https://github.com/Anniepoo/JavaPengine.  Connecting Prolog and Java using the network typically leads to far less problems.  JPL is worthwhile if you want to dispatch many small task from Java to Prolog, i.e., where the communication overhead is dominant.

**Comment by Wouter1** [comment] 2016-05-11 12:42
Thanks, ok I will post it on the mailing list too. But it leaves me a bit puzzled, isn't this the right place to report this bug?

>in particular if it is not that clear where the bug might be.

Why do you say so? The error message seems to point quite clearly to SWI

I will try if we can test on SWI 7.3 

Prolog over network really is no option. We run millions of queries at very high rates in our system.

**Comment by JanWielemaker** [comment] 2016-05-11 12:50
> Why do you say so? The error message seems to point quite clearly to SWI

It may be a JPL issue.  It may also be an issue of multiple threads trying to load library(lists).  If that is the case, it is probably fixed in 7.3.  You could try by loading library(lists) before starting threads.

> Prolog over network really is no option. We run millions of queries at very high rates in our system.

If you are concerned about performance, try to avoid passing data to Prolog as strings.  Of course,
this is not a problem for one-time jobs such as adding code to the system.

**Comment by Wouter1** [comment] 2016-05-11 13:23
I tried on SWI 7.3.20, built from source.
I removed the code lines that were not needed and caused some confusion. This was now the test program
```
import java.util.Map;

import org.jpl7.Atom;
import org.jpl7.Compound;
import org.jpl7.Query;
import org.jpl7.Term;
import org.jpl7.Variable;
import org.jpl7.JPL;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class Zahed {
	private static final int NTHREADS = 88;

	public static void main(java.lang.String argv[]) throws InterruptedException {
		new Zahed().multiThreadTest();
	}

	public void multiThreadTest() throws InterruptedException {
		System.out.println("Multi-thread test");
		List<Thread> threads = new ArrayList<Thread>();
		for (int n = 0; n < NTHREADS; n++) {
			threads.add(runThread(n));
		}
		while (!threads.isEmpty()) {
			Thread thread = threads.get(0);
			// System.out.println("Waiting for " + thread);
			thread.join();
			threads.remove(thread);
		}
	}

	private Thread runThread(final int n) {
		Thread thread = new Thread(new Runnable() {
			@Override
			public void run() {
				try {
					testSimpleQueries(n);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		});
		thread.start();
		return thread;
	}

	private void testSimpleQueries(int n) throws InterruptedException {

		String module = "robot_" + n;
		String formula = "test :- member(3,[1,2,3,4,5])";
		insert(module, formula);
		Map<String, Term> res = query(module, "test");

		insert(module, "fibo(0,0)");
		insert(module, "fibo(1,0)");
		insert(module,
				"fibo(X,Y):-X>1, X1 is X-1, X2 is X-2, fibo(X1,Y1), fibo(X2,Y2), Y is Y1 + Y2");
		query(module, "listing");

		res = query(module, "fibo(22,Y)");
	}

	private void insert(String module, String formula) {
		String f = "assert(" + module + ":(" + formula + "))";
		// System.out.println(f);
		new Query(f).hasSolution();
	}

	@SuppressWarnings("unchecked")
	private Map<String, Term> query(String module, String formula) {
		String q = module + ":" + formula;
		// System.out.println(q);
		return new Query(q).allSolutions()[0];
	}
}

```

The result remains the same. Here's some more complete output of the errors that it gives
```
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.20)
Copyright (c) 1990-2015 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

ERROR: load_files/2: No permission to load source `'/Users/bart/lib/swipl-7.3.20/library/lists.pl'' (Non-module file already loaded into module robot_15; trying to load into robot_17)
ERROR: [Thread 6] load_files/2: No permission to load source `'/Users/bart/lib/swipl-7.3.20/library/lists.pl'' (Non-module file already loaded into module robot_15; trying to load into robot_6)
ERROR: [Thread 5] load_files/2: No permission to load source `'/Users/bart/lib/swipl-7.3.20/library/lists.pl'' (Non-module file already loaded into module robot_15; trying to load into robot_27)
ERROR: [Thread 4] load_files/2: No permission to load source `'/Users/bart/lib/swipl-7.3.20/library/lists.pl'' (Non-module file already loaded into module robot_15; trying to load into robot_14)
ERROR: [Thread 8] load_files/2: No permission to load source `'/Users/bart/lib/swipl-7.3.20/library/lists.pl'' (Non-module file already loaded into module robot_15; trying to load into robot_9)
ERROR: [Thread 9] load_files/2: No permission to load source `'/Users/bart/lib/swipl-7.3.20/library/lists.pl'' (Non-module file already loaded into module robot_15; trying to load into robot_38)
ERROR: [Thread 2] load_files/2: No permission to load source `'/Users/bart/lib/swipl-7.3.20/library/lists.pl'' (Non-module file already loaded into module robot_15; trying to load into robot_85)
ERROR: [Thread 3] load_files/2: No permission to load source `'/Users/bart/lib/swipl-7.3.20/library/lists.pl'' (Non-module file already loaded into module robot_15; trying to load into robot_56)
ERROR: [Thread 7] load_files/2: No permission to load source `'/Users/bart/lib/swipl-7.3.20/library/lists.pl'' (Non-module file already loaded into module robot_15; trying to load into robot_0)
Exception in thread "Thread-14" Exception in thread "Thread-85" Exception in thread "Thread-38" Exception in thread "Thread-27" Exception in thread "Thread-0" Exception in thread "Thread-56" Exception in thread "Thread-9" Exception in thread "Thread-17" Exception in thread "Thread-6" org.jpl7.PrologException: PrologException: error(existence_error(procedure, ':'(robot_0, '/'(member, 2))), context(':'(robot_0, '/'(test, 0)), _0))
        at org.jpl7.Query.get1(Query.java:328)
        at org.jpl7.Query.hasNext(Query.java:185)
        at org.jpl7.Query.allSolutions(Query.java:538)
        at Zahed.query(Zahed.java:80)
        at Zahed.testSimpleQueries(Zahed.java:59)
        at Zahed.access$000(Zahed.java:14)
        at Zahed$1.run(Zahed.java:43)
        at java.lang.Thread.run(Thread.java:745)
org.jpl7.PrologException: PrologException: error(existence_error(procedure, ':'(robot_56, '/'(member, 2))), context(':'(robot_56, '/'(test, 0)), _1))
        at org.jpl7.Query.get1(Query.java:328)
        at org.jpl7.Query.hasNext(Query.java:185)
        at org.jpl7.Query.allSolutions(Query.java:538)
        at Zahed.query(Zahed.java:80)
        at Zahed.testSimpleQueries(Zahed.java:59)
        at Zahed.access$000(Zahed.java:14)
        at Zahed$1.run(Zahed.java:43)
        at java.lang.Thread.run(Thread.java:745)

............
```

>If you are concerned about performance, try to avoid passing data to Prolog as strings
Yes. We don't use strings normally. The strings are only to keep this code simple.

>It may be a JPL issue. It may also be an issue of multiple threads trying to load library(lists). 

I dont see what difference that makes, once I call JPL functions it's all inside the SWI black box for me and then I suppose I post bug reports here?

**Comment by JanWielemaker** [comment] 2016-05-11 13:36
> I dont see what difference that makes, once I call JPL functions it's all inside the SWI black box for me and then I suppose I post bug reports here?

For you, may be.  For us, it is a different matter.  JPL is an extension package developed and maintained by Paul Singleton.  I doubt he tracks this issue list.  Then there are active users of
JPL that are on the list but not here and may have an idea.

But, in this case it was easy.   Load the code below in plain Prolog and it shows the same problem.
Uncomment the `:- use_module(library(lists)).` and the problem is gone.  So, there is still a race if multiple threads autoload the same predicate and the workaround is simple: make
sure the required libraries are loaded before starting threads.   I'll investigate this, but not right now.

Thanks for reporting.

```{prolog}
% :- use_module(library(lists)).

t(N) :-
	atom_concat(m, N, M),
	assert(M:(test :- member(3, [1,2,3,4,5]))),
	M:test.

test(N) :-
	forall(between(1, N, I),
	       thread_create(t(I), _, [])).
```

**Comment by Wouter1** [comment] 2016-05-11 13:55
Great! 

I doubt whether the use_module workaround is an option for us, as it requires in-depth knowledge of our users about the SWI prolog library contents where we expect them to know only basic prolog knowledge.

**Comment by JanWielemaker** [comment] 2016-05-11 14:02
If it is about basic knowledge, loading the basic libraries probably makes them happy.  It is just a workaround.  I'll try to find time to fix this properly.

**Comment by Wouter1** [comment] 2016-05-11 14:10
Yes, but other functionality needs other libraries? We saw similar messages but with different functions, like make/0. So for each built-in function you would have to use_module a different file? Should we pre-load ALL library files as a workaround just to be sure?

**Comment by JanWielemaker** [comment] 2016-05-11 14:16
That is most likely a big overkill.  It only plays a role if a library is not loaded and two threads detect
at the same time they need it.  That typically happens if multiple equivalent tasks are started by the
same parent.  For example, I've never seen this happening in SWISH, which processes quite a bit of random Prolog by concurrent users.

**Comment by Wouter1** [comment] 2016-05-11 15:03
> It only plays a role if a library is not loaded and two threads detect at the same time they need it. 

Yes we never had this problem either, up to about half a year ago. Maybe it is caused by computers getting faster, causing the chances of two threads doing the same init procedure.

One case that immediately comes to my mind: we are running hundreds of similar car-driver-agents at the same time in a traffic sim.

**Comment by Wouter1** [comment] 2016-05-12 11:07
I fitted a workaround as you suggested and I hope it will do in practice (it works for the unit tests). 

Instead of lists, I import aggregate as that seems to cover most standard SWI predicates

FYI I made a dependency graph of the SWI libraries to figure that out, the graph is here

https://github.com/goalhub/krTools/tree/develop/krLanguages/swiprologlibs/doc

**Comment by JanWielemaker** [comment] 2016-05-12 11:15
Oh, forgot to mention I pushed a fix for this (SWI-Prolog/swipl-devel@b8b7c6972db3a34cc6d3ed758f181a762cc149ef).  Will probably apply to 7.2 as well.

**Closed by JanWielemaker** 2016-05-12 11:15 UTC

**Comment by Wouter1** [comment] 2016-05-12 11:40
>Oh, forgot to mention I pushed a fix for this (SWI-Prolog/swipl-devel@b8b7c69). Will probably apply to 7.2 as well.

That's fast, I didn't expect it! 

I prefer to use official releases so better wait till the next stable. Do you have an idea when it will appear?

**Comment by JanWielemaker** [comment] 2016-05-12 11:44
At the moment I have little clue.   The devel versions are pretty stable at the moment.  Several new developments are going on.  None will affect the core stability, but I'm unsure when things will settle down.
I think you're better of picking the current version and simply update only if something is blocking you.

**Comment by Wouter1** [comment] 2016-05-12 11:51
Ok good to know. "by "current version" you mean "current stable" or "current develop"?

**Comment by JanWielemaker** [comment] 2016-05-12 11:56
current devel.  Stable is hardly ever updated.  That is planned to change with 7.4.x.  For that cycle we would like to actively backport stability patches from the devel branch.  But, no clue when ...

A good idea is to install from git.  If then you're stuck, the bug is fixed and you just cherry-pick the patch into your version, so you keep up to date with the stability patches you need and only update at planned moments to the new functionality.   You shouldn't fall too far behind as patches may no longer apply or not function properly in a too old version.

**Comment by Wouter1** [comment] 2016-05-12 12:04
Ok, thanks for the clarifications. I'll check with our group what they prefer.

>A good idea is to install from git. If then you're stuck, the bug is fixed and you just cherry-pick the patch into your version, so you keep up to date with the stability patches you need and only update at planned moments to the new functionality. You shouldn't fall too far behind as patches may no longer apply or not function properly in a too old version.

Well, it's not that easy here. Our system works purely with maven artefacts and is a *universal build*. So we create a maven artefact that, completely transparent for the user,  figures out the OS that it runs on, and installs SWI libraries and all dependencies in a temp directory (and removes it again when done).

We do not know a way to do this automatically on our build servers. Therefore preparing the SWI 'artefact' is a very complex manual process that we do only once in maybe every 2 or 3 years.
