### ISSUE TITLE
Top level, dif/2 odd answer, exception uncaught

### ISSUE THREAD

**Issue by UWN** [SWI-Prolog/issues#124] opened 2023-03-03 11:10 UTC
```
l(X) :- dif(X,a),l(X).

?- l(X). % no reaction at all
?- catch(l(X), Pat,true).
ERROR: Stack limit (1.0Gb) exceeded % unexpected
...

9.1.5 `-f none` all defaults

**Comment by JanWielemaker** [comment] 2023-03-03 15:46
Thanks.  Should be fixed with SWI-Prolog/swipl-devel@8abc88ee5110007d4cd7a0457a24a1354bc05346.    Caused by running into another exception while trying to print the exception because the logic to do the last emergency stack shift was broken.    Pushed an additional commit that tries simple printing if print_message/2 runs into an exception, so at least something is printed.

**Closed by JanWielemaker** 2023-03-03 15:46 UTC
